version: '3.4'

services:
  coreapi:
    container_name: coreapi
    build:
      context: .
      dockerfile: .docker/docker-dotnet-core.dockerfile
    image: coreapi
    ports:
      - "5000:5000"
    env_file:
      - .docker/env/app.${APP_ENV}.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks: 
      - apinet

  mssql:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:latest
    env_file: 
      - .docker/env/sql.${APP_ENV}.env
    ports:
      - "3000:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks: 
      - apinet

volumes: 
  sqlvolume:
    external: false

networks: 
  apinet:
    driver: bridge